export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";

export const FETCH_BOOKS_START = "FETCH_BOOKS_START";
export const FETCH_BOOKS_FAILED = "FETCH_BOOKS_FAILED";
export const FETCH_BOOK_DETAILS_SUCCESS = "FETCH_BOOK_DETAILS_SUCCESS";

export const FETCH_SINGLE_CATEGORY = "FETCH_SINGLE_CATEGORY";

export const NEW_BOOK = " NEW_BOOK";
export const NEW_BOOK_START = " NEW_BOOK_START";
export const NEW_BOOK_FAILED = " NEW_BOOK_FAILED";

export const UPDATE_BOOK = " UPDATE_BOOK";
export const UPDATE_BOOK_START = " UPDATE_BOOK_START";
export const UPDATE_BOOK_FAILED = " UPDATE_BOOK_FAILED";

export const FETCH_AUTHORS_START = " FETCH_AUTHORS_START";

export const FETCH_AUTHORS_SUCCESS = " FETCH_AUTHORS_SUCCESS";

export const FETCH_AUTHORS_FAILED = " FETCH_AUTHORS_FAILED";

export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";

export const FETCH_CATEGORIES_START = " FETCH_CATEGORIES_START";

export const START_FETCH_SINGLE_AUTHOR = " START_FETCH_SINGLE_AUTHOR";

export const FETCH_SINGLE_AUTHOR = " FETCH_SINGLE_AUTHOR";

export const START_FETCH_SINGLE_BOOK = " START_FETCH_SINGLE_BOOK";
export const FETCH_SINGLE_BOOK_FAILED = " FETCH_SINGLE_BOOK_FAILED";

export const NEW_AUTHOR = " NEW_AUTHOR";

export const NEW_AUTHOR_FAILED = " NEW_AUTHOR_FAILED";

export const START_NEW_AUTHOR = " START_NEW_AUTHOR";

export const UPDATE_AUTHOR = " UPDATE_AUTHOR";

export const UPDATE_AUTHOR_FAILED = " UPDATE_AUTHOR_FAILED";

export const START_UPDATE_AUTHOR = " START_UPDATE_AUTHOR";

export const START_UPDATE_CATEGORY = " START_UPDATE_CATEGORY";

export const START_NEW_CATEGORY = " START_NEW_CATEGORY";

export const START_NEW_CATEGORY_FAILED = " START_NEW_CATEGORY_FAILED";

export const START_FETCH_SINGLE_CATEGORY = " START_FETCH_SINGLE_CATEGORY";

export const NEW_CATEGORY = " NEW_CATEGORY";

export const NEW_CATEGORY_FAILED = " NEW_CATEGORY_FAILED";

export const UPDATE_CATEGORY = " UPDATE_CATEGORY";
export const UPDATE_CATEGORY_FAILED = " UPDATE_CATEGORY_FAILED";

export const FETCH_SINGLE_CATEGORY_FAILED = " FETCH_SINGLE_CATEGORY_FAILED";

export const FETCH_CATEGORIES_SUCCESS = " FETCH_CATEGORIES_SUCCESS";

export const FETCH_CATEGORIES_FAILED = " FETCH_CATEGORIES_FAILED";
